FROM arm64v8/fedora:33
RUN dnf module -y enable cri-o:1.20 && dnf install -y cri-o cri-tools
RUN dnf install -y conntrack \
    iptables-services \ 
    iproute \
    procps-ng
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/arm64/kubectl" && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
COPY microshift /usr/local/bin/microshift
COPY unit /usr/lib/systemd/system/microshift.service
ADD kubelet-cgroups.conf /etc/systemd/system.conf.d/kubelet-cgroups.conf
ADD crio.conf /etc/cni/net.d/100-crio-bridge.conf
RUN systemctl enable microshift.service
RUN systemctl enable crio 
CMD [ "/sbin/init" ]
